### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by thevenomsnake** [Koowah/Steam_reviews_scraper#2]
Hello, this script seems to grab reviews in an infinite loop.

**Comment by Koowah** [comment]
Hi !

The infinite loop you're talking about is most likely the While True loop in the **run file**. You'll notice that there's a **break** statement in the try block. 

The reason I did that is that the SteamWorks API sometimes returns an incomplete review list i.e the last review cursor of the sequence is pointed at too early. I haven't figured why this happens, but the infinite loop allows the program to scrap a sequence, and restart the process if the retrieved list doesn't have all the necessary elements. (You get the number of total reviews in a specific field in the first review query)

Do **let me know** if the explanation isn't clear or if you'd like a notebook that explains how the Steam API works. I have one ready, just didn't post it yet.

Cheers =)

**Comment by thevenomsnake** [comment]
Thanks !
